apiVersion: v1
kind: PersistentVolume
metadata:
        name: "pv-local-delete"
        labels:
                volume: local
spec:
        accessModes:
                - ReadWriteOnce
        capacity:
                storage: 2Gi
        persistentVolumeReclaimPolicy: Delete
        nfs:
                server: 32.239.253.147
                path: /data1
