apiVersion: v1
kind: PersistentVolume
metadata:
        name: "pv-local"
        labels:
                volume: local
spec:
        accessModes:
                - ReadWriteOnce
        capacity:
                storage: 1Gi
        PersistentVolumeReclaimPolicy: recycle
        hostPath:
                path: /tmp/data
