apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: "pvc1-local"
        labels:
                volume: local
spec:
        storageClassName: ""
        resources:
                requests:
                        storage: 2Gi
        accessModes:
                - ReadWriteOnce
