apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: "pvc-local"
        labels:
                volume: local
spec:
        storageClassName: ""
        resources:
                requests:
                        storage: 500Mi
        accessModes:
                - ReadWriteOnce
