apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment-1
spec:
  selector:
    matchLabels:
      app: web-server-1
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web-server-1
    spec:
      containers:
      - name: web-server-1
        image: vimal13/apache-webserver-php
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: mypod-pvc
      volumes:
      - name: mypod-pvc
        persistentVolumeClaim:
          claimName: pvc1-local

