apiVersion: v1
kind: ReplicationController
metadata:
        name: "my-rc1"

spec:
        selector:
                app: web
        template:
                metadata:
                        name: "mypodrepcontrol"
                        labels:
                                app: web
                spec:
                        containers:
                                - name: "myc1"
                                  image: "vimal13/apache-webserver-php"
                        
