apiVersion: v1
kind: Pod
metadata:
        name: "volume-pod"
        labels:
                app: "volume-pod"
spec:
        containers:
                - name: myc1
                  image: vimal13/apache-webserver-php
                  ports:
                          - containerPort: 80
                  
                  volumeMounts:
                          - name: data-volume
                            mountPath: /var/www/html
        volumes:
                - name: data-volume
                  hostPath:
                    path: /data1                
