apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: vimal13/apache-webserver-php
        ports:
        - containerPort: 80
