apiVersion: v1                           
kind: Pod

metadata:
        name: myweb

spec:
        containers:
                - name: mycontainer
                  image: vimal13/apache-webserver-php

        expose: 80
        type: NodePort
