apiVersion: v1
kind: Service
metadata:
        name: db
        labels:
                app: postgres-service
spec:
        ports:
                - targetPort: 5432
                  port: 5432
        selector:
                app: postgres-pod
