apiVersion: v1
kind: Pod
metadata:
        name: redis-pod
        labels:
                app: redis-pod
                application: voting
spec:
        containers:
                - name: redis
                  image: redis
                  ports:
                          - containerPort: 6379

