apiVersion: v1
kind: Service
metadata:
        name: result-service
        labels:
                app: result-service
spec:
        ports:
                - targetPort: 80
                  port: 80
                  nodePort: 30005
        type: NodePort
        selector:
                app: result-app-pod

