apiVersion: v1
kind: Pod
metadata:
        name: mysql-pod
        labels:
                app: mysql-pod
spec:
        containers:
                - name: mysql
                  image: mysql
                  env:
                          - name: "MYSQL_ROOT_PASSWORD"
                            value: 123
                          - name: "MYSQL_DATABASE"
                            value: abc
                          - name: "MYSQL_USER"
                            value: rahul
                          - name: "MYSQL_PASSWORD"
                            value: 123 
